# MODIFICAR ENCABEZADO !!!

# 1. Exploratory Data Analysis

## 1.2. Air Carrier Financial Reports (Form 41 Financial Data)

### 1.2.2. Schedule P-12(a) Fuel

Source: https://www.transtats.bts.gov/Tables.asp?DB_ID=135&DB_Name=Air%20Carrier%20Financial%20Reports%20%28Form%2041%20Financial%20Data%29

<em>Note</em>: Over time both the code and the name of a carrier may change and the same code or name may be assumed by a different airline. To ensure that you are analyzing data from the same airline, TranStats provides four airline-specific variables that identify one and only one carrier or its entity: Airline ID (AirlineID), Unique Carrier Code (UniqueCarrier), Unique Carrier Name (UniqueCarrierName), and Unique Entity (UniqCarrierEntity). A unique airline (carrier) is defined as one holding and reporting under the same DOT certificate regardless of its Code, Name, or holding company/corporation. US Airways and America West started to report combined on-time data in January 2006 and combined traffic and financial data in October 2007 following their 2005 merger announcement. Delta and Northwest began reporting jointly in January 2010 following their 2008 merger announcement. Continental Micronesia was combined into Continental Airlines in December 2010 and joint reporting began in January 2011. Atlantic Southeast and ExpressJet began reporting jointly in January 2012. United and Continental began reporting jointly in January 2012 following their 2010 merger announcement. Endeavor (9E) operated as Pinnacle prior to August 2013. Envoy (MQ) operated as American Eagle prior to April 2014. Southwest (WN) and AirTran (FL) began reporting jointly in January 2015 following their 2011 merger announcement. American (AA) and US Airways (US) began reporting jointly as AA in July 2015 following their 2013 merger announcement. Alaska (AS) and Virgin America (VX) began reporting jointly as AS in April 2018 following their 2016 merger announcement.
        
- **P12A_fuel**:
    - **Summary**:
        - Air Carrier Financial : Schedule P-12(a)
    - **Description**:
        - This table contains monthly reported fuel costs, and gallons of fuel consumed, by air carrier and category of fuel use, including scheduled and non-scheduled service for domestic and international traffic regions. Data since 2000 are available for major, national, and regional air carriers subject to reporting requirements. For earlier data, go to [Fuel Cost and Consumption 1977-1999](http://www.bts.gov/xml/fuel/report/src/index.xml).
    - **File**:
        - 494124489_T_F41SCHEDULE_P12A.zip

___

In [1]:
# Import libraries to be used:

import pandas as pd
import numpy as np
import os.path
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import warnings # warnings.filterwarnings(action='ignore') # https://docs.python.org/3/library/warnings.html#the-warnings-filter
# from zipfile import ZipFile # De momento no ha hecho falta

In [2]:
# Show all columns and rows in DataFrames
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None) # It greatly slows down the output display and freezes the kernel

# Show in notebook
%matplotlib inline

# style -> plt.style.available
# plt.style.use('seaborn')
plt.style.use('ggplot')

# theme
sns.set_theme(context='notebook',
              style="darkgrid") # {darkgrid, whitegrid, dark, white, ticks}

# color_palette -> https://seaborn.pydata.org/generated/seaborn.color_palette.html#seaborn.color_palette
palette = sns.color_palette("flare", as_cmap=True);

In [3]:
if os.name == 'nt': # Windows
    root = r"C:\Users\turge\CompartidoVM\0.TFM"
    print("Running on Windows.")
elif os.name == 'posix': # Ubuntu
    root = "/home/dsc/shared/0.TFM"
    print("Running on Ubuntu.")
print("root path\t", root)

Running on Windows.
root path	 C:\Users\turge\CompartidoVM\0.TFM

___

In [4]:
csv_path = os.path.join(root,
                        "Raw_Data",
                        "US_DoT",
                        "494124489_T_F41SCHEDULE_P52.zip")
csv_path

'C:\\Users\\turge\\CompartidoVM\\0.TFM\\Raw_Data\\US_DoT\\494124489_T_F41SCHEDULE_P52.zip'

In [5]:
# Since 'pd.read_csv' works fine with zipped csv files, we can proceed directly:
cols = pd.read_csv(csv_path, nrows=1).columns # After normally importing it, an undesired extra blank column is loaded
df5 = pd.read_csv(csv_path,
                  encoding='latin1',
                  usecols=cols[:-1]) # This way, the extra column is disregarded for the loading process
df5

,PILOT_FLY_OPS,OTH_FLT_FLY_OPS,TRAIN_FLY_OPS,PERS_EXP_FLY_OPS,PRO_FLY_OPS,INTERCHG_FLY_OPS,FUEL_FLY_OPS,OIL_FLY_OPS,RENTAL_FLY_OPS,OTHER_FLY_OPS,INS_FLY_OPS,BENEFITS_FLY_OPS,INCIDENT_FLY_OPS,PAY_TAX_FLY_OPS,OTH_TAX_FLY_OPS,OTHER_EXP_FLY_OPS,TOT_FLY_OPS,AIRFRAME_LABOR,ENGINE_LABOR,AIRFRAME_REPAIR,ENGINE_REPAIRS,INTERCHG_CHARG,AIRFRAME_MATERIALS,ENGINE_MATERIALS,AIRFRAME_ALLOW,AIRFRAME_OVERHAULS,ENGINE_ALLOW,ENGINE_OVERHAULS,TOT_DIR_MAINT,AP_MT_BURDEN,TOT_FLT_MAINT_MEMO,NET_OBSOL_PARTS,AIRFRAME_DEP,ENGINE_DEP,PARTS_DEP,ENG_PARTS_DEP,OTH_FLT_EQUIP_DEP,OTH_FLT_EQUIP_DEP_GRP_I,FLT_EQUIP_A_EXP,FLY_OPS_EXP_I_A,TOT_AIR_OP_EXPENSES,DEV_N_PREOP_EXP,OTH_INTANGIBLES,EQUIP_N_HANGAR_DEP,G_PROP_DEP,CAP_LEASES_DEP,TOTAL_AIR_HOURS,AIR_DAYS_ASSIGN,AIR_FUELS_ISSUED,AIRCRAFT_CONFIG,AIRCRAFT_GROUP,AIRCRAFT_TYPE,AIRLINE_ID,UNIQUE_CARRIER,UNIQUE_CARRIER_NAME,CARRIER,CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER_GROUP_NEW,CARRIER_GROUP,YEAR,QUARTER
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,587.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,587.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,587.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,441,19704,CO,Continental Air Lines Inc.,CO,Continental Air Lines Inc.,01220,D,3,3,1990,1
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,450,19704,CO,Continental Air Lines Inc.,CO,Continental Air Lines Inc.,01220,D,3,3,1990,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,454,19704,CO,Continental Air Lines Inc.,CO,Continental Air Lines Inc.,01220,D,3,3,1990,1
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,461,19704,CO,Continental Air Lines Inc.,CO,Continental Air Lines Inc.,01220,D,3,3,1990,1
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1446.0,2014.0,843.0,11775.0,55.0,NaN,NaN,NaN,9,9,999,19704,CO,Continental Air Lines Inc.,CO,Continental Air Lines Inc.,01220,D,3,3,1990,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54910,376414.0,0.0,2721.0,9422.0,0.0,0.0,140325.0,682.0,18811.0,0.0,3919.0,61224.0,0.0,16865.0,3846.0,0.0,634229.0,12912.0,-38.0,18324.0,709.0,0.0,9904.0,1032.0,0.0,0.0,0.0,0.0,42843.0,38044.0,80887.0,1364.0,16588.0,34862.0,24.0,0.0,759.0,NaN,0.0,0.0,768713.0,NaN,NaN,NaN,NaN,NaN,148.95,19.02,122635.08,1,6,614,19393,WN,Southwest Airlines Co.,WN,Southwest Airlines Co.,06725,D,3,3,2020,3
54911,409660.0,0.0,4092.0,23247.0,0.0,0.0,696526.0,1687.0,50509.0,0.0,5801.0,130419.0,0.0,13015.0,33283.0,0.0,1368239.0,63297.0,826.0,96858.0,133045.0,0.0,36999.0,1775.0,0.0,0.0,0.0,0.0,332800.0,70992.0,403792.0,-457.0,-22154.0,128383.0,5256.0,2581.0,1698.0,NaN,28124.0,0.0,1915462.0,NaN,NaN,NaN,NaN,NaN,403.01,45.16,348603.29,1,6,612,19393,WN,Southwest Airlines Co.,WN,Southwest Airlines Co.,06725,D,3,3,2019,4
54912,423946.0,0.0,2492.0,18821.0,0.0,0.0,589673.0,1471.0,37355.0,0.0,4158.0,88069.0,0.0,7487.0,28377.0,0.0,1201849.0,64065.0,749.0,63804.0,114369.0,0.0,29058.0,134.0,0.0,0.0,0.0,0.0,272179.0,57573.0,329752.0,347.0,91031.0,19969.0,2587.0,1206.0,940.0,NaN,14684.0,0.0,1662365.0,NaN,NaN,NaN,NaN,NaN,388.00,42.89,337720.65,1,6,612,19393,WN,Southwest Airlines Co.,WN,Southwest Airlines Co.,06725,D,3,3,2016,3
54913,447696.0,0.0,4739.0,14028.0,0.0,0.0,150549.0,688.0,30456.0,0.0,6139.0,67859.0,0.0,22234.0,1973.0,0.0,746361.0,43251.0,5836.0,43233.0,41971.0,0.0,28336.0,1682.0,0.0,0.0,0.0,0.0,164309.0,51127.0,215436.0,-2030.0,-21651.0,130835.0,5728.0,2653.0,1792.0,NaN,28230.0,0.0,1107354.0,NaN,NaN,NaN,NaN,NaN,160.83,45.30,124112.53,1,6,612,19393,WN,Southwest Airlines Co.,WN,Southwest Airlines Co.,06725,D,3,3,2020,2
54914,606178.0,0.0,4384.0,15172.0,0.0,0.0,223076.0,1085.0,35820.0,0.0,6312.0,98595.0,0.0,27160.0,6193.0,0.0,1023975.0,34709.0,-3773.0,49255.0,71800.0,0.0,26624.0,1661.0,0.0,0.0,0.0,0.0,180276.0,61266.0,241542.0,2197.0,-22860.0,131295.0,5731.0,3705.0,1780.0,NaN,27863.0,0.0,1415228.0,NaN,NaN,NaN,NaN,NaN,239.87,44.77,194952.12,1,6,612,19393,WN,Southwest Airlines Co.,WN,Southwest Airlines Co.,06725,D,3,3,2020,3

In [6]:
df5.describe()

,PILOT_FLY_OPS,OTH_FLT_FLY_OPS,TRAIN_FLY_OPS,PERS_EXP_FLY_OPS,PRO_FLY_OPS,INTERCHG_FLY_OPS,FUEL_FLY_OPS,OIL_FLY_OPS,RENTAL_FLY_OPS,OTHER_FLY_OPS,INS_FLY_OPS,BENEFITS_FLY_OPS,INCIDENT_FLY_OPS,PAY_TAX_FLY_OPS,OTH_TAX_FLY_OPS,OTHER_EXP_FLY_OPS,TOT_FLY_OPS,AIRFRAME_LABOR,ENGINE_LABOR,AIRFRAME_REPAIR,ENGINE_REPAIRS,INTERCHG_CHARG,AIRFRAME_MATERIALS,ENGINE_MATERIALS,AIRFRAME_ALLOW,AIRFRAME_OVERHAULS,ENGINE_ALLOW,ENGINE_OVERHAULS,TOT_DIR_MAINT,AP_MT_BURDEN,TOT_FLT_MAINT_MEMO,NET_OBSOL_PARTS,AIRFRAME_DEP,ENGINE_DEP,PARTS_DEP,ENG_PARTS_DEP,OTH_FLT_EQUIP_DEP,OTH_FLT_EQUIP_DEP_GRP_I,FLT_EQUIP_A_EXP,FLY_OPS_EXP_I_A,TOT_AIR_OP_EXPENSES,DEV_N_PREOP_EXP,OTH_INTANGIBLES,EQUIP_N_HANGAR_DEP,G_PROP_DEP,CAP_LEASES_DEP,TOTAL_AIR_HOURS,AIR_DAYS_ASSIGN,AIR_FUELS_ISSUED,AIRCRAFT_CONFIG,AIRCRAFT_GROUP,AIRCRAFT_TYPE,AIRLINE_ID,CARRIER_GROUP_NEW,CARRIER_GROUP,YEAR,QUARTER
count,42100.000000,21536.000000,33917.000000,41002.000000,20272.000000,10900.000000,42433.000000,27711.000000,40725.000000,21849.000000,40029.000000,40700.000000,16681.000000,40386.000000,33283.000000,29983.000000,4.476300e+04,40861.000000,33590.000000,41377.000000,37683.000000,12185.000000,42214.000000,39019.000000,20957.000000,12768.000000,20128.000000,13230.000000,43070.000000,37860.000000,43113.000000,24838.000000,36727.000000,37846.000000,38007.000000,30069.000000,25353.000000,27280.000000,19781.000000,6241.000000,4.522800e+04,4399.000000,5833.000000,8175.000000,9279.000000,5700.000000,26521.000000,26447.000000,26075.000000,54915.000000,54915.000000,54915.000000,54915.000000,54915.000000,54915.000000,54915.000000,54915.000000
mean,6919.929186,154.491979,421.430504,751.502140,71.487035,8.364261,18747.709669,27.176289,4591.492173,13.630997,150.341310,1733.208156,11.854970,414.427624,822.188672,252.018413,3.246608e+04,1402.811539,251.685987,1649.518982,1998.412978,33.513957,1124.439733,675.073206,423.301202,41.181449,583.069683,143.827134,7117.888638,3025.367654,9767.706669,209.652680,2638.102650,817.075932,221.692088,184.467465,187.192853,3120.346899,558.278331,0.259253,4.504019e+04,1387.362576,1420.452133,754.712904,4275.361168,284.538319,12.009913,1.641377,13207.202828,2.661623,6.743167,726.198944,20043.952235,2.660384,2.660384,2005.516598,2.485878
std,16550.685230,520.253289,970.088722,1446.996484,479.862218,195.696009,45294.830703,91.878626,9407.542904,55.265392,351.998034,4496.868879,92.129184,984.814095,2019.914025,1045.219531,7.096434e+04,3261.057786,647.367842,3917.781937,5800.407649,337.105410,2281.669358,2062.838801,1804.358826,561.023724,2799.578366,975.690565,14503.999242,6705.957426,19775.370193,1244.615854,5868.679181,2877.953520,574.669941,590.244606,613.680178,6328.676413,1595.529415,13.148307,9.554057e+04,4851.603169,4574.536871,2558.756029,11970.052742,801.306937,27.049857,3.449880,25347.796500,2.953946,1.458833,164.189405,300.290441,0.508481,0.508481,8.785579,1.114390
min,-5705.000000,-960.380000,-901.000000,-1729.730000,-846.080000,-536.000000,-13910.000000,-627.000000,-73273.000000,-1097.000000,-2156.060000,-14277.000000,-2503.280000,-7748.000000,-4179.180000,-16940.210000,-7.127400e+04,-4340.000000,-3773.000000,-9702.000000,-26376.880000,-5476.000000,-31192.000000,-11468.000000,-22158.000000,-9145.000000,-19047.360000,-6310.800000,-15747.000000,-15476.000000,-27593.000000,-27902.000000,-25381.000000,-4886.000000,-7982.000000,-15900.000000,-28951.000000,-26863.410000,-2879.000000,-32.000000,-3.005600e+04,-8838.000000,-1114.000000,-6063.500000,-3421.000000,-1481.440000,-56.860000,-0.070000,-1137.430000,0.000000,0.000000,7.000000,19386.000000,1.000000,1.000000,1990.000000,1.000000
25%,299.000000,0.000000,5.810000,36.612500,0.000000,0.000000,418.000000,0.000000,75.780000,0.000000,6.000000,33.335000,0.000000,19.992500,0.690000,0.000000,1.413230e+03,52.000000,0.730000,36.890000,7.000000,0.000000,36.812500,1.590000,0.000000,0.000000,0.000000,0.000000,366.000000,61.000000,487.440000,0.000000,30.580000,11.000000,6.000000,0.000000,0.000000,151.000000,0.000000,0.000000,1.960935e+03,0.000000,0.860000,9.000000,89.320000,0.000000,0.370000,0.070000,424.260000,1.000000,6.000000,625.000000,19805.000000,2.000000,2.000000,1998.000000,1.000000
50%,1817.000000,0.000000,83.000000,238.430000,0.000000,0.000000,4030.700000,6.000000,1028.630000,0.140000,43.000000,314.035000,0.000000,115.000000,137.000000,5.120000,9.009000e+03,358.000000,34.000000,366.000000,271.000000,0.000000,315.405000,61.000000,0.000000,0.000000,0.000000,0.000000,2295.000000,708.985000,3050.000000,39.000000,537.000000,149.395000,58.880000,13.000000,12.740000,809.130000,4.120000,0.000000,1.303781e+04,10.000000,114.000000,63.000000,539.070000,18.000000,2.990000,0.420000,4027.960000,1.000000,6.000000,693.000000,20007.000000,3.000000,3.000000,2006.000000,2.000000
75%,6955.250000,66.000000,415.000000,798.447500,22.502500,0.000000,17509.000000,26.000000,4639.940000,6.000000,152.000000,1553.000000,0.000000,421.000000,760.000000,72.000000,3.277510e+04,1412.000000,227.000000,1550.000000,1524.000000,0.000000,1232.000000,434.400000,109.000000,0.000000,110.935000,0.000000,7707.277500,2828.000000,10327.160000,196.000000,2714.995000,741.000000,229.010000,99.000000,128.840000,3455.077500,359.090000,0.000000,4.684706e+04,506.000000,967.330000,385.000000,3091.540000,184.962500,12.460000,1.630000,16138.240000,2.000000,8.000000,819.000000,20344.000000,3.000000,3.000000,2013.000000,3.000000
max,606178.000000,9612.000000,16781.000000,26642.000000,49729.470000,9289.550000,930873.000000,8040.000000,148227.000000,1707.000000,14930.000000,130419.000000,3539.000000,27838.000000,37992.000000,20647.170000,1.368239e+06,78353.000000,15344.000000,98442.000000,137362.000000,17940.160000,59425.000000,51883.560000,26584.000000,12979.030000,98468.820000,17077.680000,350739.000000,127336.000000,425747.000000,36537.000000,201304.000000,133277.000000,41010.150000,19387.000000,13285.000000,294309.000000,45475.000000,853.000000,1.915462e+06,68903.000000,214043.030000,29537.000000,548352.000000,10568.000000,735.670000,45.640000,357903.470000,9.000000,9.000000,999.000000,21712.000000,3.000000,3.000000,2020.000000,4.000000

In [7]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54915 entries, 0 to 54914
Data columns (total 63 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   PILOT_FLY_OPS            42100 non-null  float64
 1   OTH_FLT_FLY_OPS          21536 non-null  float64
 2   TRAIN_FLY_OPS            33917 non-null  float64
 3   PERS_EXP_FLY_OPS         41002 non-null  float64
 4   PRO_FLY_OPS              20272 non-null  float64
 5   INTERCHG_FLY_OPS         10900 non-null  float64
 6   FUEL_FLY_OPS             42433 non-null  float64
 7   OIL_FLY_OPS              27711 non-null  float64
 8   RENTAL_FLY_OPS           40725 non-null  float64
 9   OTHER_FLY_OPS            21849 non-null  float64
 10  INS_FLY_OPS              40029 non-null  float64
 11  BENEFITS_FLY_OPS         40700 non-null  float64
 12  INCIDENT_FLY_OPS         16681 non-null  float64
 13  PAY_TAX_FLY_OPS          40386 non-null  float64
 14  OTH_TAX_FLY_OPS          33283 non-null  float64
 15  OTHER_EXP_FLY_OPS        29983 non-null  float64
 16  TOT_FLY_OPS              44763 non-null  float64
 17  AIRFRAME_LABOR           40861 non-null  float64
 18  ENGINE_LABOR             33590 non-null  float64
 19  AIRFRAME_REPAIR          41377 non-null  float64
 20  ENGINE_REPAIRS           37683 non-null  float64
 21  INTERCHG_CHARG           12185 non-null  float64
 22  AIRFRAME_MATERIALS       42214 non-null  float64
 23  ENGINE_MATERIALS         39019 non-null  float64
 24  AIRFRAME_ALLOW           20957 non-null  float64
 25  AIRFRAME_OVERHAULS       12768 non-null  float64
 26  ENGINE_ALLOW             20128 non-null  float64
 27  ENGINE_OVERHAULS         13230 non-null  float64
 28  TOT_DIR_MAINT            43070 non-null  float64
 29  AP_MT_BURDEN             37860 non-null  float64
 30  TOT_FLT_MAINT_MEMO       43113 non-null  float64
 31  NET_OBSOL_PARTS          24838 non-null  float64
 32  AIRFRAME_DEP             36727 non-null  float64
 33  ENGINE_DEP               37846 non-null  float64
 34  PARTS_DEP                38007 non-null  float64
 35  ENG_PARTS_DEP            30069 non-null  float64
 36  OTH_FLT_EQUIP_DEP        25353 non-null  float64
 37  OTH_FLT_EQUIP_DEP_GRP_I  27280 non-null  float64
 38  FLT_EQUIP_A_EXP          19781 non-null  float64
 39  FLY_OPS_EXP_I_A          6241 non-null   float64
 40  TOT_AIR_OP_EXPENSES      45228 non-null  float64
 41  DEV_N_PREOP_EXP          4399 non-null   float64
 42  OTH_INTANGIBLES          5833 non-null   float64
 43  EQUIP_N_HANGAR_DEP       8175 non-null   float64
 44  G_PROP_DEP               9279 non-null   float64
 45  CAP_LEASES_DEP           5700 non-null   float64
 46  TOTAL_AIR_HOURS          26521 non-null  float64
 47  AIR_DAYS_ASSIGN          26447 non-null  float64
 48  AIR_FUELS_ISSUED         26075 non-null  float64
 49  AIRCRAFT_CONFIG          54915 non-null  int64
 50  AIRCRAFT_GROUP           54915 non-null  int64
 51  AIRCRAFT_TYPE            54915 non-null  int64
 52  AIRLINE_ID               54915 non-null  int64
 53  UNIQUE_CARRIER           54792 non-null  object
 54  UNIQUE_CARRIER_NAME      54915 non-null  object
 55  CARRIER                  54694 non-null  object
 56  CARRIER_NAME             54915 non-null  object
 57  UNIQUE_CARRIER_ENTITY    54915 non-null  object
 58  REGION                   54915 non-null  object
 59  CARRIER_GROUP_NEW        54915 non-null  int64
 60  CARRIER_GROUP            54915 non-null  int64
 61  YEAR                     54915 non-null  int64
 62  QUARTER                  54915 non-null  int64
dtypes: float64(49), int64(8), object(6)
memory usage: 26.4+ MB

Additional information on each column meaning can be found [here](https://www.transtats.bts.gov/Fields.asp?Table_ID=297&SYS_Table_Name=T_F41SCHEDULE_P52&User_Table_Name=Schedule%20P-5.2&Year_Info=1&First_Year=1990&Last_Year=2020&Rate_Info=0&Frequency=Quarterly&Data_Frequency=Annual,Quarterly).

There are some missing values. Let's further delve into it:

In [24]:
# Absolute number of missing values by column:
for i, number in enumerate(df5.isna().sum()):
    print(df5.isna().sum().index[i], "\t",  number)

PILOT_FLY_OPS 	 12815
OTH_FLT_FLY_OPS 	 33379
TRAIN_FLY_OPS 	 20998
PERS_EXP_FLY_OPS 	 13913
PRO_FLY_OPS 	 34643
INTERCHG_FLY_OPS 	 44015
FUEL_FLY_OPS 	 12482
OIL_FLY_OPS 	 27204
RENTAL_FLY_OPS 	 14190
OTHER_FLY_OPS 	 33066
INS_FLY_OPS 	 14886
BENEFITS_FLY_OPS 	 14215
INCIDENT_FLY_OPS 	 38234
PAY_TAX_FLY_OPS 	 14529
OTH_TAX_FLY_OPS 	 21632
OTHER_EXP_FLY_OPS 	 24932
TOT_FLY_OPS 	 10152
AIRFRAME_LABOR 	 14054
ENGINE_LABOR 	 21325
AIRFRAME_REPAIR 	 13538
ENGINE_REPAIRS 	 17232
INTERCHG_CHARG 	 42730
AIRFRAME_MATERIALS 	 12701
ENGINE_MATERIALS 	 15896
AIRFRAME_ALLOW 	 33958
AIRFRAME_OVERHAULS 	 42147
ENGINE_ALLOW 	 34787
ENGINE_OVERHAULS 	 41685
TOT_DIR_MAINT 	 11845
AP_MT_BURDEN 	 17055
TOT_FLT_MAINT_MEMO 	 11802
NET_OBSOL_PARTS 	 30077
AIRFRAME_DEP 	 18188
ENGINE_DEP 	 17069
PARTS_DEP 	 16908
ENG_PARTS_DEP 	 24846
OTH_FLT_EQUIP_DEP 	 29562
OTH_FLT_EQUIP_DEP_GRP_I 	 27635
FLT_EQUIP_A_EXP 	 35134
FLY_OPS_EXP_I_A 	 48674
TOT_AIR_OP_EXPENSES 	 9687
DEV_N_PREOP_EXP 	 50516
OTH_INTANGIBLES 	 49082
EQUIP_N_HANGAR_DEP 	 46740
G_PROP_DEP 	 45636
CAP_LEASES_DEP 	 49215
TOTAL_AIR_HOURS 	 28394
AIR_DAYS_ASSIGN 	 28468
AIR_FUELS_ISSUED 	 28840
AIRCRAFT_CONFIG 	 0
AIRCRAFT_GROUP 	 0
AIRCRAFT_TYPE 	 0
AIRLINE_ID 	 0
UNIQUE_CARRIER 	 123
UNIQUE_CARRIER_NAME 	 0
CARRIER 	 221
CARRIER_NAME 	 0
UNIQUE_CARRIER_ENTITY 	 0
REGION 	 0
CARRIER_GROUP_NEW 	 0
CARRIER_GROUP 	 0
YEAR 	 0
QUARTER 	 0

In [25]:
# Relative frequency of missing values by column:
for i, number in enumerate(df5.isna().sum() / len(df5) * 100):
    print((df5.isna().sum() / len(df5) * 100).index[i], "\t",  number)

PILOT_FLY_OPS 	 23.33606482746062
OTH_FLT_FLY_OPS 	 60.783028316489116
TRAIN_FLY_OPS 	 38.23727578985705
PERS_EXP_FLY_OPS 	 25.335518528635166
PRO_FLY_OPS 	 63.08476736775016
INTERCHG_FLY_OPS 	 80.15114267504325
FUEL_FLY_OPS 	 22.72967313120277
OIL_FLY_OPS 	 49.53837749248839
RENTAL_FLY_OPS 	 25.839934444140944
OTHER_FLY_OPS 	 60.21305654192843
INS_FLY_OPS 	 27.1073477192024
BENEFITS_FLY_OPS 	 25.885459346262408
INCIDENT_FLY_OPS 	 69.62396430847674
PAY_TAX_FLY_OPS 	 26.45725211690795
OTH_TAX_FLY_OPS 	 39.39178730765729
OTHER_EXP_FLY_OPS 	 45.401074387690066
TOT_FLY_OPS 	 18.486752253482656
AIRFRAME_LABOR 	 25.592278976600202
ENGINE_LABOR 	 38.83274150960575
AIRFRAME_REPAIR 	 24.652644996813255
ENGINE_REPAIRS 	 31.379404534280255
INTERCHG_CHARG 	 77.81116270600018
AIRFRAME_MATERIALS 	 23.12847127378676
ENGINE_MATERIALS 	 28.946553764909407
AIRFRAME_ALLOW 	 61.83738504962214
AIRFRAME_OVERHAULS 	 76.74952198852772
ENGINE_ALLOW 	 63.346990803969774
ENGINE_OVERHAULS 	 75.90822179732314
TOT_DIR_MAINT 	 21.569698625147957
AP_MT_BURDEN 	 31.05708822726031
TOT_FLT_MAINT_MEMO 	 21.491395793499045
NET_OBSOL_PARTS 	 54.77009924428663
AIRFRAME_DEP 	 33.120276791404905
ENGINE_DEP 	 31.08258217244833
PARTS_DEP 	 30.789401802786127
ENG_PARTS_DEP 	 45.24446872439224
OTH_FLT_EQUIP_DEP 	 53.83228626058454
OTH_FLT_EQUIP_DEP_GRP_I 	 50.32322680506237
FLT_EQUIP_A_EXP 	 63.978876445415644
FLY_OPS_EXP_I_A 	 88.6351634343986
TOT_AIR_OP_EXPENSES 	 17.63998907402349
DEV_N_PREOP_EXP 	 91.98943822270782
OTH_INTANGIBLES 	 89.37812983702085
EQUIP_N_HANGAR_DEP 	 85.11335700628244
G_PROP_DEP 	 83.10297732859875
CAP_LEASES_DEP 	 89.62032231630702
TOTAL_AIR_HOURS 	 51.705362833469906
AIR_DAYS_ASSIGN 	 51.840116543749424
AIR_FUELS_ISSUED 	 52.517527087316765
AIRCRAFT_CONFIG 	 0.0
AIRCRAFT_GROUP 	 0.0
AIRCRAFT_TYPE 	 0.0
AIRLINE_ID 	 0.0
UNIQUE_CARRIER 	 0.22398251843758535
UNIQUE_CARRIER_NAME 	 0.0
CARRIER 	 0.40244013475371027
CARRIER_NAME 	 0.0
UNIQUE_CARRIER_ENTITY 	 0.0
REGION 	 0.0
CARRIER_GROUP_NEW 	 0.0
CARRIER_GROUP 	 0.0
YEAR 	 0.0
QUARTER 	 0.0

In [10]:
csv_path = os.path.join(root,
                        "Raw_Data",
                        "US_DoT",
                        "494124489_T_F41SCHEDULE_P7.zip")
csv_path

'C:\\Users\\turge\\CompartidoVM\\0.TFM\\Raw_Data\\US_DoT\\494124489_T_F41SCHEDULE_P7.zip'

In [11]:
# Since 'pd.read_csv' works fine with zipped csv files, we can proceed directly:
cols = pd.read_csv(csv_path, nrows=1).columns # After normally importing it, an undesired extra blank column is loaded
df6 = pd.read_csv(csv_path,
                  encoding='latin1',
                  usecols=cols[:-1]) # This way, the extra column is disregarded for the loading process
df6

,AIR_OP_EXPENSE,FL_ATT_EXPENSE,FOOD_EXPENSE,OTH_IN_FL_EXPENSE,PAX_SVC_EXPENSE,LINE_SVC_EXPENSE,CONTROL_EXPENSE,LANDING_FEES,AIR_SVC_EXPENSE,TRAFFIC_EXP_PAX,TRAFFIC_EXP_CARGO,TRAFFIC_EXP_OTH,TRAFFIC_EXPENSE,RES_EXP_PAX,RES_EXP_CARGO,RES_EXP_OTH,RES_EXPENSE,AD_EXP_PAX,AD_EXP_CARGO,AD_EXP_INST,AD_EXPENSE,ADMIN_EXPENSE,DEPR_EXP_MAINT,AMORTIZATION,TRANSPORT_EXP,TOTAL_OP_EXPENSE,MAINT_PROP_EQUIP,DEPR_PROP_EQUIP,MAINT_DEPR,SVC_SALES_OP_EXP,AIRLINE_ID,UNIQUE_CARRIER,UNIQUE_CARRIER_NAME,CARRIER,CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER_GROUP_NEW,CARRIER_GROUP,YEAR,QUARTER
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.00,15.00,NaN,NaN,-15.00,-15.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20437,FL,AirTran Airways Corporation,FL,AirTran Airways Corporation,16030,L,3,3,2007,4
1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,20.76,0.00,0.00,20.76,-0.03,0.0,0.00,-0.03,-0.01,0.00,0.00,0.00,20.72,0.00,0.00,0.00,20.72,20436,F9,Frontier Airlines Inc.,F9,Frontier Airlines Inc.,16461,L,3,3,2020,2
2,0.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.03,NaN,NaN,NaN,NaN,20357,ER,"Astar USA, LLC",ER,Astar Air Cargo Inc.,16170,A,2,2,2007,4
3,0.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.42,NaN,NaN,NaN,NaN,20357,ER,"Astar USA, LLC",ER,Astar Air Cargo Inc.,16170,A,2,2,2010,3
4,0.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.42,NaN,NaN,NaN,NaN,20357,ER,"Astar USA, LLC",ER,Astar Air Cargo Inc.,16170,A,2,2,2008,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5705,2977005.64,387471.90,130599.42,8923.99,526995.32,50117.81,54787.40,96158.85,201064.06,131728.88,278175.82,66711.12,476615.82,111296.20,16.90,126347.03,237660.13,0.00,0.0,12987.04,12987.04,1656594.97,41.49,8159.56,1909550.94,8150097.69,42900.71,100522.01,143422.72,3263541.11,19805,AA,American Airlines Inc.,AA,American Airlines Inc.,0A050,D,3,3,2020,1
5706,2984295.08,370915.94,141048.56,12357.77,524322.27,57564.04,63269.47,99961.44,220794.94,127982.19,264274.52,56760.88,449017.59,110922.71,548.11,148172.09,259642.91,0.00,0.0,23552.08,23552.08,814814.79,88.88,5327.42,1812828.39,7197052.62,33002.72,69365.55,102368.27,2399929.15,19805,AA,American Airlines Inc.,AA,American Airlines Inc.,0A050,D,3,3,2018,4
5707,2986050.69,365429.63,146419.92,11748.53,523598.08,58714.92,70358.73,102693.85,231767.50,123268.99,257721.01,60811.62,441801.61,111212.24,129.42,146381.34,257723.00,0.00,0.0,20562.55,20562.55,841453.58,481.18,7481.25,1833740.96,7241794.71,26527.03,70607.28,97134.31,2422003.06,19805,AA,American Airlines Inc.,AA,American Airlines Inc.,0A050,D,3,3,2018,3
5708,3024564.95,381697.12,145684.79,12985.41,540367.31,59500.73,61954.50,108392.15,229847.38,126759.31,270740.55,62223.74,459723.60,116778.66,17.44,153560.24,270356.34,0.00,0.0,31799.13,31799.13,834190.13,83.56,7506.67,1924763.38,7445532.76,34303.82,88026.50,122330.32,2496204.43,19805,AA,American Airlines Inc.,AA,American Airlines Inc.,0A050,D,3,3,2019,4
5709,3499002.00,252292.00,113626.00,67325.00,433243.00,113424.00,74977.00,85681.00,274082.00,473729.00,143537.00,0.00,617266.00,339740.00,14756.00,0.00,354496.00,56293.00,184.0,0.00,56477.00,325805.00,2894.00,30644.00,1224259.00,6909068.00,59671.00,31229.00,90900.00,2185807.00,19790,DL,Delta Air Lines Inc.,DL,Delta Air Lines Inc.,01260,D,3,3,2014,4

In [12]:
df6.describe()

,AIR_OP_EXPENSE,FL_ATT_EXPENSE,FOOD_EXPENSE,OTH_IN_FL_EXPENSE,PAX_SVC_EXPENSE,LINE_SVC_EXPENSE,CONTROL_EXPENSE,LANDING_FEES,AIR_SVC_EXPENSE,TRAFFIC_EXP_PAX,TRAFFIC_EXP_CARGO,TRAFFIC_EXP_OTH,TRAFFIC_EXPENSE,RES_EXP_PAX,RES_EXP_CARGO,RES_EXP_OTH,RES_EXPENSE,AD_EXP_PAX,AD_EXP_CARGO,AD_EXP_INST,AD_EXPENSE,ADMIN_EXPENSE,DEPR_EXP_MAINT,AMORTIZATION,TRANSPORT_EXP,TOTAL_OP_EXPENSE,MAINT_PROP_EQUIP,DEPR_PROP_EQUIP,MAINT_DEPR,SVC_SALES_OP_EXP,AIRLINE_ID,CARRIER_GROUP_NEW,CARRIER_GROUP,YEAR,QUARTER
count,5.709000e+03,4713.000000,4709.000000,4698.000000,4746.000000,5605.000000,5609.000000,5681.000000,5703.000000,4659.000000,5205.000000,3231.000000,5673.000000,4502.000000,4803.000000,4055.000000,5549.000000,4210.000000,4065.000000,2671.000000,5320.000000,5.699000e+03,5363.000000,5133.000000,4.831000e+03,5.709000e+03,5153.000000,5654.000000,5680.000000,5.703000e+03,5710.000000,5710.000000,5710.000000,5710.000000,5710.000000
mean,3.268330e+05,39214.027087,14876.207018,6975.267746,60606.316091,16600.333936,9886.191920,13087.106052,39074.936602,35916.627358,33944.514580,9127.772581,65839.696148,45212.166513,2608.395953,14467.970064,49511.790110,7334.256086,1075.699717,1329.063253,7293.207934,4.958764e+04,1082.930436,2935.070425,1.318664e+05,7.145893e+05,7178.218147,6837.544232,13318.458551,2.764583e+05,20005.520140,2.916287,2.916287,2005.240630,2.486165
std,4.638452e+05,61205.916004,23821.952550,11682.445074,91120.048244,38043.147556,14977.327697,20371.373436,65710.617763,70011.026797,59782.782417,20980.269636,104810.394580,79788.804012,5433.327394,30377.454314,85640.858422,15338.199679,7562.179503,3917.273331,12689.034612,9.604367e+04,3080.420082,6759.298808,3.569860e+05,1.102459e+06,14470.193376,14772.787702,25371.519573,4.283439e+05,299.515497,0.276981,0.276981,8.678886,1.113808
min,0.000000e+00,-668.430000,-5699.670000,-13516.000000,0.000000,-3964.000000,-4851.000000,-4739.000000,-1166.000000,-189762.000000,-188054.000000,-17091.000000,-13858.600000,-378.990000,-2192.370000,-8725.000000,-387.000000,-509296.000000,-4155.000000,-77802.000000,-265125.000000,-2.015950e+05,-6063.500000,-6834.000000,-7.589000e+03,3.000000e-02,-11106.000000,-632.560000,-8823.000000,-5.129630e+04,19386.000000,2.000000,2.000000,1990.000000,1.000000
25%,4.399405e+04,3768.430000,720.930000,459.402500,5942.660000,752.540000,969.000000,1146.000000,4591.785000,1127.685000,1124.000000,39.960000,4075.000000,1764.500000,59.225000,31.875000,2134.630000,82.715000,0.000000,0.000000,291.937500,3.928000e+03,16.000000,64.170000,2.671600e+02,7.835300e+04,243.000000,395.250000,926.750000,2.911185e+04,19805.000000,3.000000,3.000000,1998.000000,1.000000
50%,1.611830e+05,13078.910000,4458.000000,2379.500000,21261.705000,4526.000000,4407.870000,5426.190000,15764.870000,9142.000000,7920.000000,1366.760000,23811.000000,12801.635000,442.000000,1477.000000,13061.000000,1915.000000,27.000000,29.000000,2516.000000,1.717000e+04,112.740000,666.000000,6.036650e+03,2.934045e+05,1768.000000,2034.960000,3794.775000,1.064640e+05,19977.000000,3.000000,3.000000,2006.000000,2.000000
75%,3.838310e+05,48277.000000,20285.000000,8129.750000,79178.232500,15797.000000,12528.000000,15645.000000,46507.500000,33735.000000,35866.000000,10649.335000,73926.000000,47094.750000,2471.240000,15579.000000,52789.490000,9271.250000,368.000000,900.000000,8846.805000,5.079300e+04,700.460000,3074.000000,5.696950e+04,7.738640e+05,6969.000000,6704.382500,12946.507500,3.195060e+05,20304.000000,3.000000,3.000000,2013.000000,3.000000
max,3.499002e+06,561094.000000,205255.000000,126133.000000,685815.000000,465796.000000,146610.590000,154716.560000,611323.000000,698226.000000,466375.270000,207845.500000,766481.390000,496628.000000,61714.000000,215893.930000,501141.000000,104013.000000,291462.000000,43387.000000,175577.000000,2.152874e+06,29537.000000,229197.950000,2.544532e+06,8.150098e+06,159091.000000,548352.000000,611175.000000,3.400202e+06,21171.000000,3.000000,3.000000,2020.000000,4.000000

In [13]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5710 entries, 0 to 5709
Data columns (total 41 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   AIR_OP_EXPENSE         5709 non-null   float64
 1   FL_ATT_EXPENSE         4713 non-null   float64
 2   FOOD_EXPENSE           4709 non-null   float64
 3   OTH_IN_FL_EXPENSE      4698 non-null   float64
 4   PAX_SVC_EXPENSE        4746 non-null   float64
 5   LINE_SVC_EXPENSE       5605 non-null   float64
 6   CONTROL_EXPENSE        5609 non-null   float64
 7   LANDING_FEES           5681 non-null   float64
 8   AIR_SVC_EXPENSE        5703 non-null   float64
 9   TRAFFIC_EXP_PAX        4659 non-null   float64
 10  TRAFFIC_EXP_CARGO      5205 non-null   float64
 11  TRAFFIC_EXP_OTH        3231 non-null   float64
 12  TRAFFIC_EXPENSE        5673 non-null   float64
 13  RES_EXP_PAX            4502 non-null   float64
 14  RES_EXP_CARGO          4803 non-null   float64
 15  RES_EXP_OTH            4055 non-null   float64
 16  RES_EXPENSE            5549 non-null   float64
 17  AD_EXP_PAX             4210 non-null   float64
 18  AD_EXP_CARGO           4065 non-null   float64
 19  AD_EXP_INST            2671 non-null   float64
 20  AD_EXPENSE             5320 non-null   float64
 21  ADMIN_EXPENSE          5699 non-null   float64
 22  DEPR_EXP_MAINT         5363 non-null   float64
 23  AMORTIZATION           5133 non-null   float64
 24  TRANSPORT_EXP          4831 non-null   float64
 25  TOTAL_OP_EXPENSE       5709 non-null   float64
 26  MAINT_PROP_EQUIP       5153 non-null   float64
 27  DEPR_PROP_EQUIP        5654 non-null   float64
 28  MAINT_DEPR             5680 non-null   float64
 29  SVC_SALES_OP_EXP       5703 non-null   float64
 30  AIRLINE_ID             5710 non-null   int64
 31  UNIQUE_CARRIER         5698 non-null   object
 32  UNIQUE_CARRIER_NAME    5710 non-null   object
 33  CARRIER                5698 non-null   object
 34  CARRIER_NAME           5710 non-null   object
 35  UNIQUE_CARRIER_ENTITY  5710 non-null   object
 36  REGION                 5710 non-null   object
 37  CARRIER_GROUP_NEW      5710 non-null   int64
 38  CARRIER_GROUP          5710 non-null   int64
 39  YEAR                   5710 non-null   int64
 40  QUARTER                5710 non-null   int64
dtypes: float64(30), int64(5), object(6)
memory usage: 1.8+ MB

Additional information on each column meaning can be found [here](https://www.transtats.bts.gov/Fields.asp?Table_ID=278&SYS_Table_Name=T_F41SCHEDULE_P7&User_Table_Name=Schedule%20P-7&Year_Info=1&First_Year=1990&Last_Year=2020&Rate_Info=0&Frequency=Quarterly&Data_Frequency=Annual,Quarterly).

There are some missing values. Let's further delve into it:

In [14]:
# Absolute number of missing values by column:
df6.isna().sum()

AIR_OP_EXPENSE              1
FL_ATT_EXPENSE            997
FOOD_EXPENSE             1001
OTH_IN_FL_EXPENSE        1012
PAX_SVC_EXPENSE           964
LINE_SVC_EXPENSE          105
CONTROL_EXPENSE           101
LANDING_FEES               29
AIR_SVC_EXPENSE             7
TRAFFIC_EXP_PAX          1051
TRAFFIC_EXP_CARGO         505
TRAFFIC_EXP_OTH          2479
TRAFFIC_EXPENSE            37
RES_EXP_PAX              1208
RES_EXP_CARGO             907
RES_EXP_OTH              1655
RES_EXPENSE               161
AD_EXP_PAX               1500
AD_EXP_CARGO             1645
AD_EXP_INST              3039
AD_EXPENSE                390
ADMIN_EXPENSE              11
DEPR_EXP_MAINT            347
AMORTIZATION              577
TRANSPORT_EXP             879
TOTAL_OP_EXPENSE            1
MAINT_PROP_EQUIP          557
DEPR_PROP_EQUIP            56
MAINT_DEPR                 30
SVC_SALES_OP_EXP            7
AIRLINE_ID                  0
UNIQUE_CARRIER             12
UNIQUE_CARRIER_NAME         0
CARRIER                    12
CARRIER_NAME                0
UNIQUE_CARRIER_ENTITY       0
REGION                      0
CARRIER_GROUP_NEW           0
CARRIER_GROUP               0
YEAR                        0
QUARTER                     0
dtype: int64

In [15]:
# Relative frequency of missing values by column:
df6.isna().sum() / len(df6) * 100

AIR_OP_EXPENSE            0.017513
FL_ATT_EXPENSE           17.460595
FOOD_EXPENSE             17.530648
OTH_IN_FL_EXPENSE        17.723292
PAX_SVC_EXPENSE          16.882662
LINE_SVC_EXPENSE          1.838879
CONTROL_EXPENSE           1.768827
LANDING_FEES              0.507881
AIR_SVC_EXPENSE           0.122592
TRAFFIC_EXP_PAX          18.406305
TRAFFIC_EXP_CARGO         8.844133
TRAFFIC_EXP_OTH          43.415061
TRAFFIC_EXPENSE           0.647986
RES_EXP_PAX              21.155867
RES_EXP_CARGO            15.884413
RES_EXP_OTH              28.984238
RES_EXPENSE               2.819615
AD_EXP_PAX               26.269702
AD_EXP_CARGO             28.809107
AD_EXP_INST              53.222417
AD_EXPENSE                6.830123
ADMIN_EXPENSE             0.192644
DEPR_EXP_MAINT            6.077058
AMORTIZATION             10.105079
TRANSPORT_EXP            15.394046
TOTAL_OP_EXPENSE          0.017513
MAINT_PROP_EQUIP          9.754816
DEPR_PROP_EQUIP           0.980736
MAINT_DEPR                0.525394
SVC_SALES_OP_EXP          0.122592
AIRLINE_ID                0.000000
UNIQUE_CARRIER            0.210158
UNIQUE_CARRIER_NAME       0.000000
CARRIER                   0.210158
CARRIER_NAME              0.000000
UNIQUE_CARRIER_ENTITY     0.000000
REGION                    0.000000
CARRIER_GROUP_NEW         0.000000
CARRIER_GROUP             0.000000
YEAR                      0.000000
QUARTER                   0.000000
dtype: float64

In [16]:
df5.columns

Index(['PILOT_FLY_OPS', 'OTH_FLT_FLY_OPS', 'TRAIN_FLY_OPS', 'PERS_EXP_FLY_OPS',
       'PRO_FLY_OPS', 'INTERCHG_FLY_OPS', 'FUEL_FLY_OPS', 'OIL_FLY_OPS',
       'RENTAL_FLY_OPS', 'OTHER_FLY_OPS', 'INS_FLY_OPS', 'BENEFITS_FLY_OPS',
       'INCIDENT_FLY_OPS', 'PAY_TAX_FLY_OPS', 'OTH_TAX_FLY_OPS',
       'OTHER_EXP_FLY_OPS', 'TOT_FLY_OPS', 'AIRFRAME_LABOR', 'ENGINE_LABOR',
       'AIRFRAME_REPAIR', 'ENGINE_REPAIRS', 'INTERCHG_CHARG',
       'AIRFRAME_MATERIALS', 'ENGINE_MATERIALS', 'AIRFRAME_ALLOW',
       'AIRFRAME_OVERHAULS', 'ENGINE_ALLOW', 'ENGINE_OVERHAULS',
       'TOT_DIR_MAINT', 'AP_MT_BURDEN', 'TOT_FLT_MAINT_MEMO',
       'NET_OBSOL_PARTS', 'AIRFRAME_DEP', 'ENGINE_DEP', 'PARTS_DEP',
       'ENG_PARTS_DEP', 'OTH_FLT_EQUIP_DEP', 'OTH_FLT_EQUIP_DEP_GRP_I',
       'FLT_EQUIP_A_EXP', 'FLY_OPS_EXP_I_A', 'TOT_AIR_OP_EXPENSES',
       'DEV_N_PREOP_EXP', 'OTH_INTANGIBLES', 'EQUIP_N_HANGAR_DEP',
       'G_PROP_DEP', 'CAP_LEASES_DEP', 'TOTAL_AIR_HOURS', 'AIR_DAYS_ASSIGN',
       'AIR_FUELS_ISSUED', 'AIRCRAFT_CONFIG', 'AIRCRAFT_GROUP',
       'AIRCRAFT_TYPE', 'AIRLINE_ID', 'UNIQUE_CARRIER', 'UNIQUE_CARRIER_NAME',
       'CARRIER', 'CARRIER_NAME', 'UNIQUE_CARRIER_ENTITY', 'REGION',
       'CARRIER_GROUP_NEW', 'CARRIER_GROUP', 'YEAR', 'QUARTER'],
      dtype='object')

In [17]:
df6.columns

Index(['AIR_OP_EXPENSE', 'FL_ATT_EXPENSE', 'FOOD_EXPENSE', 'OTH_IN_FL_EXPENSE',
       'PAX_SVC_EXPENSE', 'LINE_SVC_EXPENSE', 'CONTROL_EXPENSE',
       'LANDING_FEES', 'AIR_SVC_EXPENSE', 'TRAFFIC_EXP_PAX',
       'TRAFFIC_EXP_CARGO', 'TRAFFIC_EXP_OTH', 'TRAFFIC_EXPENSE',
       'RES_EXP_PAX', 'RES_EXP_CARGO', 'RES_EXP_OTH', 'RES_EXPENSE',
       'AD_EXP_PAX', 'AD_EXP_CARGO', 'AD_EXP_INST', 'AD_EXPENSE',
       'ADMIN_EXPENSE', 'DEPR_EXP_MAINT', 'AMORTIZATION', 'TRANSPORT_EXP',
       'TOTAL_OP_EXPENSE', 'MAINT_PROP_EQUIP', 'DEPR_PROP_EQUIP', 'MAINT_DEPR',
       'SVC_SALES_OP_EXP', 'AIRLINE_ID', 'UNIQUE_CARRIER',
       'UNIQUE_CARRIER_NAME', 'CARRIER', 'CARRIER_NAME',
       'UNIQUE_CARRIER_ENTITY', 'REGION', 'CARRIER_GROUP_NEW', 'CARRIER_GROUP',
       'YEAR', 'QUARTER'],
      dtype='object')

In [18]:
df5_2020 = df5.loc[df5['YEAR'] == 2020, ['UNIQUE_CARRIER', 'CARRIER_NAME', 'TOTAL_DIRECT', 'TOTAL_INDIRECT', 'TOTAL_OP_EXPENSE', 'AIRCRAFT_FUEL']]
df5_2020

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['TOTAL_DIRECT', 'TOTAL_INDIRECT', 'TOTAL_OP_EXPENSE', 'AIRCRAFT_FUEL'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

In [ ]:
df5g = df5_2020.groupby('CARRIER_NAME').sum().sort_values(by='TOTAL_OP_EXPENSE', ascending=False).head(10)
df5g

In [ ]:
sorted(list(df5['CARRIER_NAME'].dropna().unique()))